apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment # name of the app
  namespace: gke-terra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myApp  # which pods are part of the deployment
  template:
    metadata:
      labels:
        app: myApp  #name of the pod(s)
    spec:
      containers:
      - name: app
        image: europe-west3-docker.pkg.dev/terraform-cicd-pipeline-509514/gke-demo-repo/gke-demo-app:latest
        ports:  #defines container ports
        - name: http
          containerPort: 8080   # is target port of service

        resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 200m
        readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
        livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
