name: deployment
run-name: ${{github.actor}} is auto deploying 

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: 'write'     # that GitHub can issue the OIDC token
  contents: 'read'

concurrency:
  group: deploy
  cancel-in-progress: false   # never cancel a deploy halfway

env:
  PROJECT_ID: 'terraform-cicd-pipeline-509514'
  REGION: 'europe-west3'
  REPOSITORY_ID: 'gke-demo-repo'     # of artifact registry
  IMAGE_NAME: 'gke-demo-app'

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v7'

      # step 1: authenticate
      # log into google cloud
      - name: 'auth'
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{env.PROJECT_ID}}
          workload_identity_provider: '${{vars.WIF_PROVIDER}}'
          service_account: '${{vars.WIF_SERVICE_ACCOUNT}}'
      
      # make gcloud available and configured
      - name: 'set up cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # step 2: build & push
      # configure docker for artifact registry
      - name: 'docker auth'
        run: gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev
      
      - name: 'set image uri'
        run: echo "IMAGE_URI=${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY_ID}}/${{env.IMAGE_NAME}}:${{github.sha}}" >> "$GITHUB_ENV"

      - name: 'build image'
        run: docker build . --tag ${{env.IMAGE_URI}}
        working-directory: app

      - name: 'push image'
        run: docker push ${{env.IMAGE_URI}}

      # step 3: deploy
 




